version: '3'

services:
  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '81:3333'
    expose:
      - '81'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=development
      - APP_KEY=_GfVvTlnpAk1_Rm_fUD-bBGkSHa8P-ov
      - DRIVE_DISK=local
      - DB_CONNECTION=mysql
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB_NAME=gethewars
      - BASE_URL=https://swapi.dev/api
#    links:
#      - db
#    command: >
#      node ace migration:run
#      && npm run dev
#    command: npm run dev

#  db:
#    image: mysql
#    restart: unless-stopped
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_DATABASE: 'demo_adonis'
#      # So you don't have to use root, but you can if you like
##      MYSQL_USER: 'dev'
#      # You can use whatever password you like
#      MYSQL_PASSWORD: 'password'
#      MYSQL_ROOT_PASSWORD: 'password'
#    ports:
#      # <Port exposed> : < MySQL Port running inside container>
#      - '3306:3306'
#    expose:
#      # Opens port 3306 on the container
#      - '3306'
#      # Where our data will be persisted
##    volumes:
##      - './.mysql-data/db:/var/lib/mysql'
##      - './initial.sql:/docker-entrypoint-initdb.d/initial.sql'
#    healthcheck:
#      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
#      timeout: 20s
#      retries: 10
